notifications:
  email: false
  irc: "chat.freenode.net#Heather"

env:
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install: cabal-1.18 update
script:
 - cabal-1.18 install --only-dependencies
 - cabal-1.18 configure
 - cabal-1.18 install
 - runhaskell test/test.hs
